[package]
name = "lrpc-macros"
version = "0.1.0"
authors = ["lipogem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
