[package]
name = "lrpc"
version = "0.1.0"
authors = ["lipogem"]
edition = "2018"
description = "local rpc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lrpc-macros = { path = "./lrpc-macros", version = "0.1.0" }
